### ISSUE TITLE
this function is rending the the app?

### ISSUE THREAD

**Issue by hassaanhameed786** [Haris-Noori/TeslaApp#1]
https://github.com/Haris-Noori/TeslaApp/blob/e15a2fee2a375f1b5c2487733ada83644dfe6f33/App.js#L15

**Comment by Haris-Noori** [comment]
> https://github.com/Haris-Noori/TeslaApp/blob/e15a2fee2a375f1b5c2487733ada83644dfe6f33/App.js#L15

So shall I use `const App` instead ?

**Comment by hassaanhameed786** [comment]
optimizing the performance 
 app by using the const App()...

**Comment by mubeenghauri** [comment]
@hassaanhameed786 it would be better if u fork this repo, make a new branch, make the change ur suggesting and push to ur branch, then make a pull request. You'll be officially contributing to this app. (Y) 
Good eye hassy :eyes: :+1:
